#!/usr/bin/env bash
# regen-base-patches.sh -- (re)generate patches/base/*.patch and
# patches/addon/*.patch from the fork's stacked series, walking the
# manifest in order (e.g. C1 -> C2 -> ... -> A5).
#
# Each patch is exported as `git diff DIFF_BASE TIP` where DIFF_BASE
# is the merge-base of the previous manifest row's tip with the
# current row's tip. In the linear case (each branch fork'd from the
# previous branch's tip) the merge-base equals the previous tip, so
# the result is identical to a naive sequential diff. In the
# non-linear case (e.g. a follow-on commit landed on the previous
# branch but the current branch still fork'd off the previous
# branch's base commit) the merge-base correctly resolves to the
# actual fork point.
#
# This assumes every fork branch already descends from the target
# NVIDIA tag. Rebasing the stack onto a NEW upstream tag (the
# tag-bump path) is intentionally NOT implemented here -- see
# docs/superpowers/specs/2026-05-22-dynamic-patch-composition-design.md.
#
# Usage: regen-base-patches.sh [--fork DIR] [--tag TAG|--nvidia-tag TAG]
#   --fork  default: $FORK_REPO or /root/open-gpu-kernel-modules
#   --tag   default: NVIDIA_OPEN_TAG from nvidia-version.env (then Dockerfile)
set -eu

repo_root="$(cd "$(dirname "$0")/.." && pwd)"
. "$repo_root/tools/lib/manifest.sh"
. "$repo_root/tools/lib/nvidia-version.sh"

fork="${FORK_REPO:-/root/open-gpu-kernel-modules}"
tag=""
while [ $# -gt 0 ]; do
    case "$1" in
        --fork) fork="$2"; shift 2 ;;
        --tag|--nvidia-tag) tag="$2"; shift 2 ;;
        *) echo "regen: unknown arg '$1'" >&2; exit 2 ;;
    esac
done
if [ -z "$tag" ]; then
    if nvidia_version_load "$repo_root" 2>/dev/null; then
        tag="$NVIDIA_OPEN_TAG"
    else
        tag="$(nvidia_dockerfile_tag "$repo_root/Dockerfile" 2>/dev/null || true)"
    fi
fi
[ -n "$tag" ] || { echo "regen: could not determine target tag" >&2; exit 1; }
nvidia_version_validate_tag "$tag" || exit 1
[ -d "$fork/.git" ] || { echo "regen: fork repo not found at $fork" >&2; exit 1; }

manifest="$repo_root/patches/manifest"
base_dir="$repo_root/patches/base"
[ -f "$manifest" ] || { echo "regen: no manifest at $manifest" >&2; exit 1; }
mkdir -p "$base_dir"

tag_sha="$(git -C "$fork" rev-parse --verify "refs/tags/$tag^{commit}" 2>/dev/null)" \
    || { echo "regen: tag '$tag' not found in $fork" >&2; exit 1; }

state="$base_dir/.regen-state"
{
    echo "# regen-base-patches.sh state -- generated $(date -u +%FT%TZ)"
    echo "# base tag: $tag ($tag_sha)"
} > "$state"

prev_ref="$tag_sha"
prev_name="$tag"
count=0
while read -r id layer up src; do
    case "$layer" in base|addon) ;; *) continue ;; esac
    [ "$up" = "-" ] || continue          # upstreamed: nothing to generate
    case "$src" in
        fork:*) branch="${src#fork:}" ;;
        *) echo "regen: row '$id' has non-fork source '$src'" >&2; exit 1 ;;
    esac
    sha="$(git -C "$fork" rev-parse --verify "$branch^{commit}" 2>/dev/null)" \
        || { echo "regen: branch '$branch' not found in $fork" >&2; exit 1; }
    if ! git -C "$fork" merge-base --is-ancestor "$tag_sha" "$sha"; then
        echo "regen: '$branch' does not descend from tag '$tag'." >&2
        echo "       Rebase the fork stack onto $tag manually first --" >&2
        echo "       tag-bump rebasing is out of scope for this tool" >&2
        echo "       (see the design doc)." >&2
        exit 1
    fi
    diff_base="$(git -C "$fork" merge-base "$prev_ref" "$sha" 2>/dev/null)" \
        || { echo "regen: '$branch' shares no history with '$prev_name'" >&2; exit 1; }
    out="$repo_root/patches/$layer/$id.patch"
    mkdir -p "$repo_root/patches/$layer"
    {
        echo "# GENERATED by tools/regen-base-patches.sh -- DO NOT EDIT."
        echo "# Patch:  $id"
        echo "# Source: fork branch $branch @ $sha"
        echo "# Base:   $prev_name @ $diff_base"
        echo "# Regenerate with: tools/regen-base-patches.sh"
        echo "#"
        git -C "$fork" diff "$diff_base" "$sha"
    } > "$out"
    echo "$id  $branch  $sha" >> "$state"
    shortstat="$(git -C "$fork" diff --shortstat "$diff_base" "$sha" | sed 's/^ *//')"
    echo "regen: wrote ${out#$repo_root/}  ($branch -- $shortstat)"
    prev_ref="$sha"
    prev_name="$branch"
    count=$((count + 1))
done <<EOF
$(manifest_rows "$manifest")
EOF

echo "regen: generated $count patch(es) (base + addon) into patches/"

validate="$repo_root/tools/validate-patchset.sh"
if [ -x "$validate" ]; then
    echo "regen: validating composed set ..."
    "$validate"
else
    echo "regen: next -- run tools/validate-patchset.sh to compile-check the set."
fi
